const buttonLogic = require('../buttonLogic.js')

buttonsDefault = [
    {   
        text: 'VHF2\nR800L1',
        goTo: 'vhf2',
    },  
    {   
        text: 'Overhead\nFront ->',
        goTo: 'overhead',
    },  
    {   
        text: 'Counter\nmeasures',
        goTo: 'counter',
    },      
    {   
        text: 'ARBIS',
        goTo: 'arbis',
    },    
    {   
        text: 'Wall',
        goTo: 'wall',
    },   
    {   
        text: 'Engine\nAPU',
        goTo: 'engine',
    },
    {   
        text: 'Datalink',
        goTo: 'datalink',
    },
    {   
        text: 'HUD\nTV\nLandLight',
        goTo: 'hud',
    },   
    {   
        text: 'PVI800',
        goTo: 'pvi800-1',
    },
    {   
        text: 'ADF\nFlare',
        goTo: 'flare',
    },
    {   
        text: 'Targeting',
        goTo: 'targeting',
    },    
    {   
        text: 'Front\nLeft',
        goTo: 'front',
    },
    {   
        text: 'Weap',
        goTo: 'weapons',
    },  
    {   
        text: 'AP',
        goTo: 'ap',
    },
    {   
        text: 'VHF1\nR828',
        goTo: 'vhf1',
    },
]


buttonsEngineApu = [
    {   
        text: '<- Back',
        goTo: 'default',
    }, 
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        maxStatus: 0,
        text: 'Start',
        apiSend: 'ENG_START',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        maxStatus: 0,
        text: 'Start\nAbort',
        apiSend: 'ENG_STOP',
    },            
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        maxStatus: 0,
        text: 'APU\nSTOP',
        apiSend: 'ENG_APU_STOP',
    },   

    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenButton,
        sendState: false,
        text: 'Fuel\nOpen',
        apiGet: 'APU_FUEL_VLV_OPEN',
    }, 
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenButton,
        sendState: false,
        text: 'Oil\nPresure',
        apiGet: 'APU_OIL_PRESS',
    }, 
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.yellowButton,
        sendState: false,
        text: 'Valve\nOpen',
        apiGet: 'ENG_START_VLV_OPEN',
    }, 
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        text: ['Startup', 'Crank', 'FalseS'],
        apiSend: 'ENG_STARTUP_MODE',
    },                
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['APU', 'Left ENG', 'Right ENG', 'Turbo Gear'],
        apiSend: 'ENG_SELECTOR',
    },                
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenButton,
        sendState: false,
        text: 'RPM\nAbort',
        apiGet: 'APU_STOP_RPM',
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenButton,
        sendState: false,
        text: 'Started',
        apiGet: 'APU_OPER',
    },     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        nameId: 'apuTemp',
        stateToText: (state) => Math.round(state / 72.81667) + 'C',
        text: 'n/a',
        apiGet: 'APU_TEMP',
        dynamicState: true,
    },       
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        nameId: 'leftEngineRPM',
        stateToText: (state) => Math.round(state / 600) + '%',
        text: 'n/a',
        apiGet: 'ENG_L_RPM',
        dynamicState: true,
    },          
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        nameId: 'rightEngineRPM',
        stateToText: (state) => Math.round(state / 600) + '%',
        text: 'n/a',
        apiGet: 'ENG_R_RPM',
        dynamicState: true,
    },          
]

buttonsTargeting = [
    {   
        text: '<- Back',
        goTo: 'default',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'Train'],
        apiSend: 'WEAPONS_TRAINING_MODE',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'Auto\nTurn',
        maxStatus: 0,
        apiSend: 'WEAPONS_AUTO_TURN_BTN',
        apiGet: 'WEAPONS_AUTO_TURN_LED',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'Air\nH/O',
        maxStatus: 0,
        apiSend: 'WEAPONS_FORWARD_HEMI_TARGET_BTN',
        apiGet: 'WEAPONS_FORWARD_HEMI_TARGET_LED',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        text: ['Movable', 'Fixed', 'ManBackup', 'Navigation', 'Failure'],
        apiSend: 'WEAPONS_MODE',
    },          
    {},     
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'Air',
        maxStatus: 0,
        apiSend: 'WEAPONS_AIRBORNE_TARGET_BTN',
        apiGet: 'WEAPONS_AIRBORNE_TARGET_LED',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'Mov\nGND',
        maxStatus: 0,
        apiSend: 'WEAPONS_GROUND_TARGET_BTN',
        apiGet: 'WEAPONS_GROUND_TARGET_LED',
    },    
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'K041 ON'],
        apiSend: 'K041_POWER',
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'HMS'],
        apiSend: 'HMS_POWER',
    },                     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['GunSight', 'AutoTrack'],
        apiSend: 'WEAPONS_AUTOTRACK_GUNSIGHT',
    },                     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'Laser'],
        apiSend: 'LASER_STANDBY',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'Reset',
        maxStatus: 0,
        apiSend: 'WEAPONS_TARGET_RESET_BTN',
        apiGet: 'WEAPONS_TARGET_RESET_LED',
    },                           
]


buttonsVhf2 = [
    {   
        text: '<- Back',
        goTo: 'default',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['FM', 'AM'],
        apiSend: 'R800_AM_FM',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.yellowButton,
        text: 'BIT\nPASS',
        maxStatus: 0,
        apiGet: 'R800_TEST_LAMP',
        sendState: false,
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['50', '100'],
        apiSend: 'R800_DATA_TRANSFER_RATE',
    },       
    {},     
    

    {},     
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        text: 'BIT',
        maxStatus: 0,
        apiSend: 'R800_TEST_BTN',
        sendState: false,
    },                  
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['VHF-2', 'VHF-1', 'SW', 'G-Intercom'],
        apiSend: 'RADIO_SELECTOR',
    },     
    
    {   
        text: 'VHF2\nFreq',
        goTo: 'vhf2freq',
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Norm', 'E121.5'],
        apiSend: 'R800_EMER_RCVR',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Off', 'ADF'],
        apiSend: 'R800_ADF',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Off', 'NRedu'],
        apiSend: 'R800_SQUELCH',
    },       
]


buttonsVhf2freq = [
    {   
        nameId: 'back',
        text: '<- Back',
        goTo: 'default',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        nameId: 'freq1',
        stateToText: (state) => {
            const ret = Math.floor(state / 10.5653)
            return ret < 5 ? ret + 10 : ret + 17
        },
        apiGet: 'R800_FREQ1_ROT',
        dynamicState: true,
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        nameId: 'freq2',
        stateToText: (state) => state + '.',
        apiGet: 'R800_FREQ2',
        dynamicState: true,
    },        
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        nameId: 'freq3',
        stateToText: (state) => state,        
        apiGet: 'R800_FREQ3',
        dynamicState: true,
    },        
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        stateToText: (state) => Math.ceil(state / 2.5466667) + ' MHz',
        nameId: 'freq4',
        apiGet: 'R800_FREQ4_ROT',
        dynamicState: true,
    },        

    {   
        nameId: 'lightBright',
        text: 'VHF2',
        goTo: 'vhf2',
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        text: '+\n10',
        sendLiterarly: 'INC',
        maxStatus: 0,
        apiSend: 'R800_FREQ1',
        dynamicState: true,
    },        
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        text: '+\n1',
        sendLiterarly: 'INC',
        maxStatus: 0,
        apiSend: 'R800_FREQ2',
        dynamicState: true,
    },        
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        text: '+\n0.1',
        sendLiterarly: 'INC',
        apiSend: 'R800_FREQ3',
        dynamicState: true,
    },        
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        text: '+\n0.01',
        sendLiterarly: 'INC',
        apiSend: 'R800_FREQ4',
        dynamicState: true,
    },        
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        text: '-\n10',
        sendLiterarly: 'DEC',
        maxStatus: 0,
        apiSend: 'R800_FREQ1',
        dynamicState: true,
    },        
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        text: '-\n1',
        sendLiterarly: 'DEC',
        maxStatus: 0,
        apiSend: 'R800_FREQ2',
        dynamicState: true,
    },        
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        text: '-\n0.1',
        sendLiterarly: 'DEC',
        apiSend: 'R800_FREQ3',
        dynamicState: true,
    },        
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        text: '-\n0.01',
        sendLiterarly: 'DEC',
        apiSend: 'R800_FREQ4',
        dynamicState: true,
    },            
]


buttonsCounter = [
    {   
        text: '<- Back',
        goTo: 'default',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.redButton,
        sendState: false,
        text: '<-',
        apiGet: 'UV26_L_DISPENSER',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blueButton,
        sendState: false,
        text: 'Seq Series\n0 = inf\n5 = 12\n7 = 15',
        apiSend: 'UV26_SERIES',
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blueButton,
        sendState: false,
        text: 'Interval (s)\n0 = 0.125\n7 = 0.25\n9 = 0.5',
        apiSend: 'UV26_INTERVAL',
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.redButton,
        sendState: false,
        text: '->',
        apiGet: 'UV26_R_DISPENSER',
    },     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.green7seg,
        sendState: false,
        nameId: 'counterDisplay',
        apiGet: 'UV26_DISPLAY',
        dynamicState: true,
    },     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        fontIndex: 4,
        text: ['<-', 'Both', '->'],
        apiSend: 'UV26_DISPENSERS_SELECTOR',
    }, 
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blueButton,
        sendState: false,
        text: 'Burst\nin 1 seq',
        apiSend: 'UV26_BURST',
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blueButton,
        sendState: false,
        text: 'Reset',
        apiSend: 'UV26_RESET',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        fontIndex: 4,
        text: ['Count', 'Prog'],
        apiSend: 'UV26_MODE',
    },       
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.redButton,
        sendState: false,
        text: 'LWR\nRESET',
        apiSend: 'LWR_RESET',
        apiGet: 'LWR_RESET',
    },    
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenButton,
        sendState: false,
        text: 'Stop',
        apiSend: 'UV26_STOP',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.redButton,
        sendState: false,
        text: 'Start',
        apiSend: 'UV26_START',
    },    
]

buttonsDatalink = [
    {   
        text: '<- Back',
        goTo: 'default',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: '1\nVehi',
        maxStatus: 0,
        apiSend: 'DLNK_TARGET_VEHICLE_BTN',
        apiGet: 'DLNK_TARGET_VEHICLE_LED',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: '2\nAAA',
        maxStatus: 0,
        apiSend: 'DLNK_TARGET_SAM_BTN',
        apiGet: 'DLNK_TARGET_SAM_LED',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: '3\nOther',
        maxStatus: 0,
        apiSend: 'DLNK_TARGET_OTHER_BTN',
        apiGet: 'DLNK_TARGET_OTHER_LED',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'Ingress',
        maxStatus: 0,
        apiSend: 'DLNK_TARGET_POINT_LED',
        apiGet: 'DLNK_TARGET_POINT_BTN',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'Wing\n1',
        maxStatus: 0,
        apiSend: 'DLNK_WINGMAN_1_BTN',
        apiGet: 'DLNK_WINGMAN_1_LED'
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'Wing\n2',
        maxStatus: 0,
        apiSend: 'DLNK_WINGMAN_2_BTN',
        apiGet: 'DLNK_WINGMAN_2_LED'
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'Wing\n3',
        maxStatus: 0,
        apiSend: 'DLNK_WINGMAN_3_BTN',
        apiGet: 'DLNK_WINGMAN_3_LED'
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'Wing\n4',
        maxStatus: 0,
        apiSend: 'DLNK_WINGMAN_4_BTN',
        apiGet: 'DLNK_WINGMAN_4_LED'
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'Wing\nAll',
        maxStatus: 0,
        apiSend: 'DLNK_WINGMAN_ALL_BTN',
        apiGet: 'DLNK_WINGMAN_ALL_LED'
    },      
    {},     
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.yellowStripeButton,
        sendState: false,
        text: 'Erase',
        maxStatus: 0,
        apiSend: 'DLNK_ERASE_BTN',
        apiGet: 'DLNK_ERASE_LED'
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.yellowStripeButton,
        sendState: false,
        text: 'Ingress\nTo',
        maxStatus: 0,
        apiSend: 'DLNK_ESCAPE_BTN',
        apiGet: 'DLNK_ESCAPE_LED'
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.yellowStripeButton,
        sendState: false,
        text: 'Send\nMemory',
        maxStatus: 0,
        apiSend: 'DLNK_SEND_BTN',
        apiGet: 'DLNK_SEND_LED'
    },  
]

buttonsOverhead = [
    {   
        text: '<- Back',
        goTo: 'default',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Wing-0%', 'Wing-10%', 'Wing-30%', 'Wing-100%'],
        apiSend: 'OP_NAV_LIGHTS',
    },         
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['WiperOff', 'Wiper3', 'Wiper2', 'Wiper1'],
        apiSend: 'OP_WINDSHIELD_WIPER',
    },         
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Off', 'SensHt'],
        apiSend: 'OP_PITOT_PORT_HEAT',
    },         
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Off', 'PilotHt'],
        apiSend: 'OP_PITOT_RAM_HEAT',
    },         
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Off', '!RotIce'],
        apiSend: 'OP_ROTOR_DEICE',
    },         
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['!Dusting', '!Icing'],
        apiSend: 'OP_ENG_DEICE',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: 'PilotHt\nTest',
        apiSend: 'OP_PITOT_HEAT_TEST',
    },   
    {},     
    {},     

    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: 'Running\nGas\nTemp',
        apiSend: 'ENG_RUNNING_EGT_TEST',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: 'Stopped\nGas\nTemp',
        apiSend: 'ENG_STOPPED_EGT_TEST',
    },  
    {},     
    {},     

    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: 'Fuel\nTest',
        apiSend: 'FUEL_TEST',
    },       
]


buttonsFront = [
    {   
        text: '<- Back',
        goTo: 'default',
    },   
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.yellowButton,
        sendState: false,
        maxStatus: 0,
        text: 'R RPM',
        apiSend: 'SC_ROTOR_RPM_BTN',
        apiGet: 'SC_ROTOR_RPM_LED',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: 'Lamp\nTest',
        apiSend: 'SC_LAMPS_TEST',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.redButton,
        sendState: false,
        text: 'MASTER\nCAUTION',
        apiSend: 'SC_MASTER_CAUTION_BTN',
        apiGet: 'SC_MASTER_CAUTION_LED',
    }, 
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'emergencyCover',
        text: 'Cover\nv',
        apiSend: 'GEAR_EMER_HYD_COVER',
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenButton,
        sendState: false,
        text: 'Left\nDown',
        apiGet: 'GEAR_L_MAIN_DOWN',
    },         
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenButton,
        sendState: false,
        text: 'Nose\nDown',
        apiGet: 'GEAR_NOSE_DOWN',
    },          
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenButton,
        sendState: false,
        text: 'Right\nDown',
        apiGet: 'GEAR_R_MAIN_DOWN',
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.redButton,
        sendState: false,
        text: 'LWR\nRESET',
        apiSend: 'LWR_RESET',
        apiGet: 'LWR_RESET',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        text: ['MainG', 'EmerG' ],
        apiSend: 'GEAR_EMER_HYD',
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        text: ['Gear ^', 'Gear v'],
        apiSend: 'GEAR_LEVER',
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: 'Laser\nReset',
        apiSend: 'LASER_RESET',
    },          
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'laserCover',
        text: 'Cover\n->',
        apiSend: 'LASER_MODE_COVER',
    },     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['LRange', 'LDesig'],
        apiSend: 'LASER_MODE',
    },  
]


buttonsWall = [
    {   
        text: '<- Back',
        goTo: 'default',
    },   
    {   
        text: 'Fire',
        goTo: 'wall-fire',
    },
    {},     
    {},     
    {},     
    

    {   
        text: 'Elect',
        goTo: 'wall-electrical1',
    },
    {   
        text: 'Pumps',
        goTo: 'wall-pumps',
    },
    {   
        text: 'Fuel',
        goTo: 'wall-fuel',
    },
    {   
        text: 'Equip',
        goTo: 'wall-equip',
    },
    {   
        text: 'Govern',
        goTo: 'wall-governors-lights',
    },
    {   
        text: 'Radio',
        goTo: 'wall-radio',
    },    
    {   
        text: 'Eject',
        goTo: 'wall-eject',
    },  
 
    {   
        text: 'AUX\ntop',
        goTo: 'aux1',
    },
    {   
        text: 'LWS\nCounter\nEkran',
        goTo: 'aux2',
    },
    {   
        text: 'Lights',
        goTo: 'lights-bright',
    },    
]


buttonsWallEquip = [
    {   
        text: '<- Back',
        goTo: 'wall',
    },  
    {   
        text: 'Fuel',
        goTo: 'wall-fuel',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'hydrcover',
        text: 'Cover\nv',
        apiSend: 'HYD_POWER_COVER',
    },  
    {},     
    {   
        text: 'Govern',
        goTo: 'wall-governors-lights',
    },

    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'weaponCover',
        text: 'Cover\nv',
        apiSend: 'WEAPONS_POWER_COVER',
    },            
    {},     
    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['HydPwr', 'OFF'],
        apiSend: 'HYD_POWER',
    },        
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'TgrNav'],
        apiSend: 'NAV_POWER',
    },        
    {   
        text: 'Lights',
        goTo: 'lights-bright',
    },  

    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'Wep-PWR'],
        apiSend: 'WEAPONS_POWER',
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', '!ColBeac'],
        apiSend: 'LIGHT_BEACON',
    },       
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: false,
        text: ['Magne', 'FliGyro', 'Manual'],
        apiSend: 'NAV_GYRO_MAG_MAN_HDG',
    },       
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'SAI'],
        apiSend: 'SAI_POWER',
    },        
    {   
        text: 'AUX\ntop',
        goTo: 'aux1',
    },  
]


buttonsWallEl1 = [
    {   
        text: '<- Back',
        goTo: 'wall',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'grndcover',
        text: 'Cover\nv',
        apiSend: 'ELEC_DC_GROUND_POWER_COVER',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'bat2cover',
        text: 'Cover\nv',
        apiSend: 'ELEC_BATTERY_2_COVER',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'bat1cover',
        text: 'Cover\nv',
        apiSend: 'ELEC_BATTERY_1_COVER',
    },   
    {   
        text: 'Pumps',
        goTo: 'wall-pumps',
    },
 
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'GND-DC'],
        apiSend: 'ELEC_DC_GROUND_POWER',
    },     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'BAT2'],
        apiSend: 'ELEC_BATTERY_2',
    },     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'BAT1'],
        apiSend: 'ELEC_BATTERY_1',
    },      
    {},     
    {   
        text: 'Radio',
        goTo: 'wall-radio',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'GND-AC'],
        apiSend: 'ELEC_AC_GROUND_POWER',
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'LEFT-AC'],
        apiSend: 'ELEC_AC_L_GEN',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'RIGHT-AC'],
        apiSend: 'ELEC_AC_R_GEN',
    },          
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Manual', 'OFF', 'Inverter'],
        apiSend: 'ELEC_DC_AC',
    },       
]


buttonsWallGovernors = [
    {   
        text: '<- Back',
        goTo: 'wall',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'lGoverCover',
        text: 'Cover\nv',
        apiSend: 'ENG_L_ENG_EEG_COVER',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'rGoverCover',
        text: 'Cover\nv',
        apiSend: 'ENG_R_ENG_EEG_COVER',
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'GGtestCover',
        text: 'Cover\nv',
        apiSend: 'ENG_EEG_GG_TEST_OPER_COVER',
    },        
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'PTtestCover',
        text: 'Cover\nv',
        apiSend: 'ENG_EEG_PT1_OPER_PT2_COVER',
    },        
    {   
        text: 'Equip',
        goTo: 'wall-equip',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'LeftGov'],
        apiSend: 'ENG_L_ENG_EEG',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'RightGov'],
        apiSend: 'ENG_R_ENG_EEG',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'GGTest'],
        apiSend: 'ENG_EEG_GG_TEST_OPER',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['PT-1 Test', 'Operatio', 'PT-2 Test'],
        apiSend: 'ENG_EEG_PT1_OPER_PT2',
    },  

    {},     
    {},     
    {   
        text: 'Lights',
        goTo: 'lights-bright',
    },      
    {   
        text: 'AUX\ntop',
        goTo: 'aux1',
    },
    {   
        text: 'LWS\nCounter\nEkran',
        goTo: 'aux2',
    },     
]


buttonsWallRadio = [
    {   
        text: '<- Back',
        goTo: 'wall',
    },   
    {   
        text: 'Elect',
        goTo: 'wall-electrical1',
    },     
    {   
        text: 'Pumps',
        goTo: 'wall-pumps',
    },  
    {   
        text: 'Fuel',
        goTo: 'wall-fuel',
    },  
    {   
        text: 'Equip',
        goTo: 'wall-equip',
    },     
    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'IntCom'],
        apiSend: 'COMM_INTERCOM_POWER',
    },           
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'VHI-1'],
        apiSend: 'COMM_VHF1_POWER',
    },           
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'VHI-2'],
        apiSend: 'COMM_VHF2_POWER',
    },     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'TLK'],
        apiSend: 'COMM_DATALINK_TLK_POWER',
    },              
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'VHF-TLK'],
        apiSend: 'COMM_DATALINK_VHF_TLK_POWER',
    },  
    {},     
    {},     
    {},     
    {},     
    {   
        text: 'Eject',
        goTo: 'wall-eject',
    },                 
]


buttonsWallFire = [
    {   
        text: '<- Back',
        goTo: 'wall',
    },   
    {   
        text: 'Elect',
        goTo: 'wall-electrical1',
    },     
    {   
        text: 'Pumps',
        goTo: 'wall-pumps',
    },  
    {   
        text: 'Fuel',
        goTo: 'wall-fuel',
    },  
    {   
        text: 'Equip',
        goTo: 'wall-equip',
    },     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.redButton,
        text: 'Left\nENG',
        maxStatus: 0,
        sendState: false,
        apiSend: 'FIREEXT_L_ENG_EXT',
        apiGet: 'FIREEXT_L_ENG_FIRE',
    },       
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.redButton,
        text: 'APU',
        maxStatus: 0,
        sendState: false,
        apiSend: 'FIREEXT_APU_EXT',
        apiGet: 'FIREEXT_APU_FIRE',
    },       
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.redButton,
        text: 'Right\nENG',
        maxStatus: 0,
        sendState: false,
        apiSend: 'FIREEXT_R_ENG_EXT',
        apiGet: 'FIREEXT_R_ENG_FIRE',
    },     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.redButton,
        text: 'Vent',
        maxStatus: 0,
        sendState: false,
        apiSend: 'FIREEXT_VENT_EXT',
        apiGet: 'FIREEXT_VENT_FIRE',
    },            
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'slectCover',
        text: 'Cover\nv',
        apiSend: 'FIREEXT_EXT_MODE_COVER',
    },         
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'slectmanCover',
        text: 'Cover\n->',
        apiSend: 'FIREEXT_AUTO_MANUAL_COVER',
    },         
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        text: ['Auto', 'Manual'],
        apiSend: 'FIREEXT_AUTO_MANUAL',
    },          
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Off', 'Alarm'],
        apiSend: 'FIREEXT_MONITOR',
    },       
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        maxStatus: 2,
        text: ['Test  3', 'Test  1', 'Test  2'],
        apiSend: 'FIREEXT_WARN_TEST',
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        fontIndex: 5,
        text: ['Test', 'Off', 'Work'],
        apiSend: 'FIREEXT_EXT_MODE',
    },
]


buttonsWallEject = [
    {   
        text: '<- Back',
        goTo: 'wall',
    },   
    {   
        text: 'Elect',
        goTo: 'wall-electrical1',
    },     
    {   
        text: 'Pumps',
        goTo: 'wall-pumps',
    },  
    {   
        text: 'Fuel',
        goTo: 'wall-fuel',
    },  
    {   
        text: 'Equip',
        goTo: 'wall-equip',
    },     
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'ejectCover1',
        text: 'Cover\nv',
        apiSend: 'EJECT_POWER_COVER',
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'ejectCover2',
        text: 'Cover\nv',
        apiSend: 'EJECT_POWER_COVER',
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'ejectCover3',
        text: 'Cover\nv',
        apiSend: 'EJECT_POWER_COVER',
    },      
    {},     
    {   
        text: 'Radio',
        goTo: 'wall-radio',
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        text: ['Eject1', 'OFF'],
        apiSend: 'EJECT_POWER_1',
    },           
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        text: ['Eject2', 'OFF'],
        apiSend: 'EJECT_POWER_2',
    },           
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        text: ['Eject3', 'OFF'],
        apiSend: 'EJECT_POWER_3',
    },  
]

buttonsWallPumps = [
    {   
        text: '<- Back',
        goTo: 'wall',
    },   
    {   
        text: 'Elect',
        goTo: 'wall-electrical1',
    },     
    {   
        text: 'Fuel',
        goTo: 'wall-fuel',
    },    
    {   
        text: 'Equip',
        goTo: 'wall-equip',
    },    
    {   
        text: 'Govern',
        goTo: 'wall-governors-lights',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'PUMP-FWD'],
        apiSend: 'FUEL_FORWARD_PUMP_POWER',
    },        
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'PUMP-AFT'],
        apiSend: 'FUEL_AFT_PUMP_POWER',
    },        
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'PUMP-INN'],
        apiSend: 'FUEL_INNER_PUMP_POWER',
    },        
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'PUMP-OUTE'],
        apiSend: 'FUEL_OUTER_PUMP_POWER',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'Meter'],
        apiSend: 'FUEL_METER_POWER',
    },    
    {   
        text: 'Radio',
        goTo: 'wall-radio',
    },   
    {},     
    {   
        text: 'Eject',
        goTo: 'wall-eject',
    },                            
    {},     
    {},     
]

buttonsWallFuel = [
    {   
        text: '<- Back',
        goTo: 'wall',
    },  
    {   
        text: 'Elect',
        goTo: 'wall-electrical1',
    },     
    {   
        text: 'Pumps',
        goTo: 'wall-pumps',
    },
    {   
        text: 'Equip',
        goTo: 'wall-equip',
    },
    {   
        text: 'Govern',
        goTo: 'wall-governors-lights',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'leftCover',
        text: 'Cover\nv',
        apiSend: 'FUEL_L_ENG_VLV_COVER',
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'rightCover',
        text: 'Cover\nv',
        apiSend: 'FUEL_R_ENG_VLV_COVER',
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'apuCover',
        text: 'Cover\nv',
        apiSend: 'FUEL_APU_VLV_COVER',
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'xfeedCover',
        text: 'Cover\nv',
        apiSend: 'FUEL_XFEED_VLV_COVER',
    },  
    {   
        text: 'Lights',
        goTo: 'lights-bright',
    },  
 
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'PUMP-LEFT'],
        apiSend: 'FUEL_L_ENG_VLV',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'PUMP-RIGHT'],
        apiSend: 'FUEL_R_ENG_VLV',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'PUMP-APU'],
        apiSend: 'FUEL_APU_VLV',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'X-FEED'],
        apiSend: 'FUEL_XFEED_VLV',
    },   
]


buttonsHud = [
    {   
        text: '<- Back',
        goTo: 'default',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: true,
        text: 'Filter',
        apiSend: 'HUD_FILTER_HANDLE',
    },  
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -4095,
        maxStatus: 65535,
        overflow: false,
        text: '-\nHUD\nBright',
        apiSend: 'HUD_BRIGHTNESS',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: +4095,
        maxStatus: 65535,
        overflow: false,
        text: '+\nHUD\nBright',
        apiSend: 'HUD_BRIGHTNESS',
        dynamicState: true,
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Night', 'Day', 'StandBy'],
        apiSend: 'HUD_MODE',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['White', 'Black'],
        apiSend: 'SHKVAL_POLARITY',
    },                
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -4095,
        maxStatus: 65535,
        overflow: false,
        text: '-\nHMS',
        apiSend: 'HMS_BRIGHTNESS',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: +2047,
        maxStatus: 65535,
        overflow: false,
        text: '+\nHMS',
        apiSend: 'HMS_BRIGHTNESS',
        dynamicState: true,
    },  
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -2048,
        maxStatus: 65535,
        overflow: false,
        text: '-\nShkval\nBright',
        apiSend: 'SHKVAL_BRIGHTNESS',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: +2048,
        maxStatus: 65535,
        overflow: false,
        text: '+\nShkval\nBright',
        apiSend: 'SHKVAL_BRIGHTNESS',
        dynamicState: true,
    },      
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -2048,
        maxStatus: 65535,
        overflow: false,
        text: '-\nShkval\nContra',
        apiSend: 'SKHVAL_CONTRAST',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: +2048,
        maxStatus: 65535,
        overflow: false,
        text: '+\nShkval\nContra',
        apiSend: 'SKHVAL_CONTRAST',
        dynamicState: true,
    },        {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Laser #1', 'Laser #2', 'Laser #3'],
        apiSend: 'LASER_CODE',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Full H', 'Declu'],
        apiSend: 'HUD_DECLUTTER',
    },          
    {   
        text: 'Landing\nlights',
        goTo: 'land',
    },    
]


buttonsLightsBrightness = [
    {   
        text: '<- Back',
        goTo: 'wall',
    },   
 
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: +4095,
        maxStatus: 65535,
        overflow: false,
        text: '+\nBlue CPT\nLight',
        apiSend: 'LIGHT_AUX_BRIGHTNESS',
        dynamicState: true,
    },    
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: +4095,
        maxStatus: 65535,
        overflow: false,
        text: '+\nSAI/ADI\nLight',
        apiSend: 'LIGHT_HSI_ADI_BRIGHTNESS',
        dynamicState: true,
    },    
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: +4095,
        maxStatus: 65535,
        overflow: false,
        text: '+\nPanels\nLight',
        apiSend: 'LIGHT_COCKPIT_BRIGHTNESS',
        dynamicState: true,
    },  
    {   
        text: 'AUX\ntop',
        goTo: 'aux1',
    },
    {   
        text: 'Govern',
        goTo: 'wall-governors-lights',
    },
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -4095,
        maxStatus: 65535,
        overflow: false,
        text: '-\nBlue CPT\nLight',
        apiSend: 'LIGHT_AUX_BRIGHTNESS',
        dynamicState: true,
    },    
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -4095,
        maxStatus: 65535,
        overflow: false,
        text: '-\nSAI/ADI\nLight',
        apiSend: 'LIGHT_HSI_ADI_BRIGHTNESS',
        dynamicState: true,
    },    
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -4095,
        maxStatus: 65535,
        overflow: false,
        text: '-\nPanels\nLight',
        apiSend: 'LIGHT_COCKPIT_BRIGHTNESS',
        dynamicState: true,
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'Interior' ],
        apiSend: 'LIGHT_CPT_INT',
    },         

    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'Rotor' ],
        apiSend: 'LIGHT_ROTOR_TIP',
    },       
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Frm0%', 'Frm10%', 'Frm30%', 'Frm100%'],
        apiSend: 'LIGHT_FORMATION',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'SAI+ADI' ],
        apiSend: 'LIGHT_ADI_SAI',
    },          
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'NVG' ],
        apiSend: 'LIGHT_COCKPIT_NVG',
    },          
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'Cockpit' ],
        apiSend: 'LIGHT_COCKPIT',
    },      
]

buttonsLand = [
    {   
        text: '<- Back',
        goTo: 'hud',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Retract', 'Off', 'Extend'],
        apiSend: 'LIGHT_LANDING_ON_RETR_OFF',
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        text: ['Main', 'Back'],
        apiSend: 'LIGHT_LANDING_MAIN_BACKUP',
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        fontIndex: 4,
        inversed: true,
        text: ['Outer', 'Auto*', 'Inner'],
        apiSend: 'ADF_NDB_MODE',
    },      
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: 'VMU\ncease',
        apiSend: 'VOICE_MSG_OFF',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: 'VMU\nrepeat',
        apiSend: 'VOICE_MSG_REPEAT',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        fontIndex: 4,
        inversed: true,
        text: ['Emerg', 'Norm'],
        apiSend: 'VOICE_MSG_EMER',
    },      
]


buttonsWeapons = [
    {   
        text: '<- Back',
        goTo: 'default',
    },       
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Moff', 'MArm'],
        apiSend: 'WEAPONS_MASTER_ARM',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.green7seg,
        sendState: false,
        nameId: 'wepType',
        apiGet: 'WEAPONS_DISPLAY_STORE_TYPE',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.green7seg,
        sendState: false,
        nameId: 'wepRem',
        apiGet: 'WEAPONS_DISPLAY_WEAPON_REMAIN',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.green7seg,
        sendState: false,
        nameId: 'ammoRem',
        apiGet: 'WEAPONS_DISPLAY_CANNON_REMAIN',
        dynamicState: true,
    },
    {},     
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: 'Jet\nExt',
        apiSend: 'WEAPONS_JETTISON_EXT',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Joff', 'JArm'],
        apiSend: 'WEAPONS_JETTISON_ARM_MODE',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: 'Jet\nATGM',
        apiSend: 'WEAPONS_EXPEDITE_ATGM_JETTISON',
    },
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Auto', 'Manual'],
        apiSend: 'WEAPONS_MANUAL_AUTO',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        fontIndex: 5,
        inversed: true,
        text: ['low', 'med', 'long'],
        apiSend: 'WEAPONS_CANNON_BURST',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['AP', 'HE'],
        apiSend: 'WEAPONS_CANNON_ROUND',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['High', 'Low'],
        apiSend: 'WEAPONS_CANNON_RATE',
    },

]


buttonsPvio800_3 = [
    {   
        text: '<- Back',
        goTo: 'pvi800-1',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        stateToText: (state) => Math.abs(Math.ceil(((state - 32767.5)+65535)%65535 / 1820.4166))%36,
        nameId: 'mag10',
        text: 'n/a',
        apiGet: 'ZMS3_MAGVAR_CNT_100_10',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        stateToText: (state) => Math.round(state / 655.35)/10 + 'deg',
        nameId: 'mag',
        text: 'n/a',
        apiGet: 'ZMS3_MAGVAR_CNT_1',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -4095,
        sendState: false,
        text: '-\nMagne',
        apiSend: 'ZMS3_MAGVAR_SELECTOR',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: +4095,
        sendState: false,
        maxStatus: 65535,
        overflow: true,
        text: '+\nMagne',
        apiSend: 'ZMS3_MAGVAR_SELECTOR',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        fontIndex: 7,
        inversed: true,
        text: ['OFF', 'CHECK', 'EDIT', 'OPER', 'SIM'],
        apiSend: 'PVI_MODES',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['UPDATE', 'INU'],
        apiSend: 'PVI_INU_FIX',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'ON'],
        apiSend: 'PVI_POWER',
    },
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -4095,
        maxStatus: 65535,
        overflow: false,
        text: '-\nBright',
        apiSend: 'PVI_BRIGHTNESS',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: +4095,
        maxStatus: 65535,
        overflow: false,
        text: '+\nBright',
        apiSend: 'PVI_BRIGHTNESS',
        dynamicState: true,
    },    

    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        fontIndex: 7,
        text: ['1', '2', '3', '4'],
        apiSend: 'DLNK_SELF_ID',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        text: ['OFF', 'Rx-Only', 'Wingman', 'CMDR'],
        apiSend: 'DLNK_MASTER_MODE',
    },
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -1,
        maxStatus: 7,
        overflow: false,
        text: '-\nScan RT',
        apiSend: 'SHKVAL_OPTICS_SCAN_RATE',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: 1,
        maxStatus: 7,
        overflow: false,
        text: '+\nScan RT',
        apiSend: 'SHKVAL_OPTICS_SCAN_RATE',
        dynamicState: true,
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        text: ['North', 'South'],
        apiSend: 'PSHK7_NORTH_SOUTH',
    },           
    
]


buttonsPvio800_2 = [
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.green7seg,
        sendState: false,
        nameId: 'line1',
        apiGet: 'PVI_LINE1_TEXT',
        goTo: 'pvi800-1',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'FIX\nPNT',
        maxStatus: 0,
        apiSend: 'PVI_FIXPOINTS_BTN',
        apiGet: 'PVI_FIXPOINTS_LED',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'SELF\nCOOR',
        maxStatus: 0,
        apiSend: 'PVI_SELF_COOR_BTN',
        apiGet: 'PVI_SELF_COOR_LED',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'T-HEAD\nTIME/DI',
        maxStatus: 0,
        apiSend: 'PVI_THDG_TIME_RANGE_BTN',
        apiGet: 'PVI_THDG_TIME_RANGE_LED',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'INU\nPREC',
        maxStatus: 0,
        apiSend: 'PVI_INU_PRECISE_ALIGN_BTN',
        apiGet: 'PVI_INU_PRECISE_ALIGN_LED',
    }, 

    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.green7seg,
        sendState: false,
        nameId: 'line2',
        apiGet: 'PVI_LINE2_TEXT',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'AIR\nFIELD',
        maxStatus: 0,
        apiSend: 'PVI_AIRFIELDS_BTN',
        apiGet: 'PVI_AIRFIELDS_LED',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'DTA\nDH',
        maxStatus: 0,
        apiSend: 'PVI_DTA_DH_BTN',
        apiGet: 'PVI_DTA_DH_LED',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'HEAD/RA\nTGT PNT',
        maxStatus: 0,
        apiSend: 'PVI_BEARING_RANGE_BTN',
        apiGet: 'PVI_BEARING_RANGE_LED',
    },             
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'INU\nNORM',
        maxStatus: 0,
        apiSend: 'PVI_INU_NORMAL_ALIGN_BTN',
        apiGet: 'PVI_INU_NORMAL_ALIGN_LED',
    },    

    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'WPT',
        maxStatus: 0,
        apiSend: 'PVI_WAYPOINTS_BTN',
        apiGet: 'PVI_WAYPOINTS_LED',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'NAV\nTGT',
        maxStatus: 0,
        apiSend: 'PVI_TARGETS_BTN',
        apiGet: 'PVI_TARGETS_LED',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'WIND\nDI/SP',
        maxStatus: 0,
        apiSend: 'PVI_WIND_HDG_SPEED_BTN',
        apiGet: 'PVI_WIND_HDG_SPEED_LED',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'INU\nRERUN',
        maxStatus: 0,
        apiSend: 'PVI_INU_INFLIGHT_REALIGN_BTN',
        apiGet: 'PVI_INU_INFLIGHT_REALIGN_LED',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'INIT\nPNT',
        maxStatus: 0,
        apiSend: 'PVI_INIT_PNT_BTN',
        apiGet: 'PVI_INIT_PNT_LED',
    },
]


buttonsPvio800_1 = [
    {   
        text: '<- Back',
        goTo: 'default',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: '-\n1',
        apiSend: 'PVI_1',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: '2',
        apiSend: 'PVI_2',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: '3',
        apiSend: 'PVI_3',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.yellowStripeButton,
        text: 'Reset',
        maxStatus: 0,
        apiSend: 'PVI_RESET_BTN',
        apiGet: 'PVI_RESET_LED',
        sendState: false,
    },
    {   
        text: 'PVI800\nfunc',
        goTo: 'pvi800-2',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: '4',
        apiSend: 'PVI_4',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: '5',
        apiSend: 'PVI_5',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: '6',
        apiSend: 'PVI_6',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: '+\n0',
        apiSend: 'PVI_0',
    },
    {   
        text: 'PVI800\nPVTz-800',
        goTo: 'pvi800-3',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: '7',
        apiSend: 'PVI_7',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: '8',
        apiSend: 'PVI_8',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: '9',
        apiSend: 'PVI_9',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.yellowStripeButton,
        text: 'Enter',
        maxStatus: 0,
        apiSend: 'PVI_ENTER_BTN',
        apiGet: 'PVI_ENTER_LED',
        sendState: false,
    },    
]


buttonsArbis = [
    {   
        text: '<- Back',
        goTo: 'default',
    },
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Off', 'On'],
        apiSend: 'ABRIS_POWER',
    },
    {},     
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -4095,
        maxStatus: 65535,
        overflow: false,
        text: '-\nBright',
        apiSend: 'ABRIS_BRIGHTNESS',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: +4095,
        maxStatus: 65535,
        overflow: false,
        text: '+\nBright',
        apiSend: 'ABRIS_BRIGHTNESS',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        text: '^\n1',
        apiSend: 'ABRIS_BTN_1',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        text: '^\n2',
        apiSend: 'ABRIS_BTN_2',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        text: '^\n3',
        apiSend: 'ABRIS_BTN_3',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        text: '^\n4',
        apiSend: 'ABRIS_BTN_4',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        text: '^\n5',
        apiSend: 'ABRIS_BTN_5',
    },

    {},     
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -4095,
        sendState: false,
        maxStatus: 65535,
        overflow: true,
        text: '-\nCursor',
        apiSend: 'ABRIS_CURSOR_ROT',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        text: 'Button\nCursor',
        apiSend: 'ABRIS_CURSOR_BTN',
        sendState: false,
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: +4095,
        sendState: false,
        overflow: true,
        maxStatus: 65535,
        text: '+\nCursor',
        apiSend: 'ABRIS_CURSOR_ROT',
        dynamicState: true,
    },
]


buttonsAp = [
    {   
        text: '<- Back',
        goTo: 'default',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.redButton,
        sendState: false,
        text: 'LWR\nRESET',
        apiSend: 'LWR_RESET',
        apiGet: 'LWR_RESET',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'HMS'],
        apiSend: 'HMS_POWER',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'Auto\nTurn',
        maxStatus: 0,
        apiSend: 'WEAPONS_AUTO_TURN_BTN',
        apiGet: 'WEAPONS_AUTO_TURN_LED',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.redButton,
        sendState: false,
        text: 'MASTER\nCAUTION',
        apiSend: 'SC_MASTER_CAUTION_BTN',
        apiGet: 'SC_MASTER_CAUTION_LED',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blueButton,
        sendState: false,
        text: 'BANK\nHOLD',
        apiSend: 'AP_BANK_HOLD_BTN',
        apiGet: 'AP_BANK_HOLD_LED',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blueButton,
        sendState: false,
        text: 'PITCH\nHOLD',
        apiSend: 'AP_PITCH_HOLD_BTN',
        apiGet: 'AP_PITCH_HOLD_LED',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.yellowButton,
        sendState: false,
        maxStatus: 0,
        text: 'R RPM',
        apiSend: 'SC_ROTOR_RPM_BTN',
        apiGet: 'SC_ROTOR_RPM_LED',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blueButton,
        sendState: false,
        text: 'FD\nAP',
        apiSend: 'AP_FD_BTN',
        apiGet: 'AP_FD_LED',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.greenStripeButton,
        sendState: false,
        text: 'Weap\nReset',
        maxStatus: 0,
        apiSend: 'WEAPONS_TARGET_RESET_BTN',
        apiGet: 'WEAPONS_TARGET_RESET_LED',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blueButton,
        sendState: false,
        text: 'HDG\nHOLD',
        apiSend: 'AP_HDG_HOLD_BTN',
        apiGet: 'AP_HDG_HOLD_LED',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blueButton,
        sendState: false,
        text: 'ALT\nHOLD',
        apiSend: 'AP_ALT_HOLD_BTN',        
        apiGet: 'AP_ALT_HOLD_LED',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        fontIndex: 4, 
        text: ['BR', '--', 'RD'],
        apiSend: 'AP_BARO_RALT',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        fontIndex: 4, 
        text: ['DH', '--', 'DT'],
        apiSend: 'AP_DH_DT',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.redButton,
        sendState: false,
        text: 'Counter\nStart',
        apiSend: 'UV26_START',
    },    
]


buttonsFlare = [
    {   
        text: '<- Back',
        goTo: 'default',
    },
    {},     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        stateToText: (state) => state == 1 ? 'Serv1\nchan' : state == 0 ? 'Serv0\nchan' : (state-1) + '\nchan',
        nameId: 'channel',
        text: 'n/a',
        apiGet: 'ADF_CHANNEL',
        dynamicState: true,
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -1,
        maxStatus: 9,
        text: '-\nChannel',
        apiSend: 'ADF_CHANNEL',
        dynamicState: true,
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        maxStatus: 9,
        overflow: false,
        text: '+\nChannel',
        apiSend: 'ADF_CHANNEL',
        dynamicState: true,
    },      
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -4095,
        overflow: false,
        maxStatus: 65535,
        text: '-\nVolume',
        apiSend: 'ADF_VOLUME',
        dynamicState: true,
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: +4095,
        overflow: false,
        maxStatus: 65535,
        text: '+\nVolume',
        apiSend: 'ADF_VOLUME',
        dynamicState: true,
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        text: ['TLF', 'TLG'],
        apiSend: 'ADF_TLF_TLG',
    },
    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        maxStatus: 0,
        text: 'ADF\nTest',
        apiSend: 'ADF_TEST',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        text: ['CMPS', 'ANT' ],
        apiSend: 'ADF_CMPS_ANT',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Off', 'On'],
        apiSend: 'FLARES_POWER',
    },
    {   
        type: buttonLogic.types.textToggle,
        maxStatus: 0,
        scheme: buttonLogic.colorScheme.grayButton,
        customFontColor: '#dd0000',
        text: 'Red\nflare',
        sendState: false,
        apiSend: 'FLARES_RED',
    },
    {   
        type: buttonLogic.types.textToggle,
        maxStatus: 0,
        scheme: buttonLogic.colorScheme.grayButton,
        customFontColor: '#00dd00',
        text: 'Green\nflare',
        sendState: false,
        apiSend: 'FLARES_GREEN',
    },
    {   
        type: buttonLogic.types.textToggle,
        maxStatus: 0,
        scheme: buttonLogic.colorScheme.grayButton,
        text: 'White\nflare',
        sendState: false,
        apiSend: 'FLARES_WHITE',
    },
    {   
        type: buttonLogic.types.textToggle,
        maxStatus: 0,
        scheme: buttonLogic.colorScheme.grayButton,
        customFontColor: '#dddd00',
        text: 'Yellow\nflare',
        sendState: false,
        apiSend: 'FLARES_YELLOW',
    },
]


buttonsVhf1 = [
    {   
        text: '<- Back',
        goTo: 'default',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        sendState: false,
        stateToText: (state) => state+1 + '\nchan',
        nameId: 'channel',
        text: 'n/a',
        apiGet: 'R828_CHANNEL',
        dynamicState: true,
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -1,
        overflow: true,
        maxStatus: 9,
        text: '-\nChannel',
        apiSend: 'R828_CHANNEL',
        dynamicState: true,
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        overflow: true,
        maxStatus: 9,
        text: '+\nChannel',
        apiSend: 'R828_CHANNEL',
        dynamicState: true,
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: 'Auto\ntune',
        apiSend: 'R828_TUNER',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.yellowButton,
        sendState: false,
        text: 'Tuning',
        apiGet: 'R828_TUNER_LAMP',
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['Off', 'NRedu'],
        apiSend: 'R828_SQUELCH',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        overflow: false,
        increment: -4095,
        maxStatus: 655535,
        text: '-\nVolume',
        apiSend: 'R828_VOLUME',
        dynamicState: true,
    },         
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        overflow: false,
        increment: 4095,
        maxStatus: 655535,
        text: '+\nVolume',
        apiSend: 'R828_VOLUME',
        dynamicState: true,
    },                      
]


buttonsAux1 = [
    {   
        text: '<- Back',
        goTo: 'wall',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: 'Left\nGov',
        apiSend: 'ENG_L_EGT_GOVERNOR',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: 'Right\nGov',
        apiSend: 'ENG_R_EGT_GOVERNOR',
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: 'Vibra',
        apiSend: 'ENG_VIBR_MONITOR',
    },     
    {},     
    {   
        text: 'LWS\nCounter\nEkran',
        goTo: 'aux2',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        sendState: false,
        text: 'Eject\ntest',
        apiSend: 'EJECT_SYS_TEST_BTN',
    },          
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        overflow: false,
        increment: -1,
        maxStatus: 6,
        text: 'Eject-',
        dynamicState: true,
        apiSend: 'EJECT_SYS_SELECTOR',
    },          
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        overflow: false,
        maxStatus: 6,
        text: 'Eject+',
        dynamicState: true,
        apiSend: 'EJECT_SYS_SELECTOR',
    }, 
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        maxStatus: 0,
        sendState: false,
        text: 'Voice\ntest',
        apiSend: 'VOICE_MSG_SYS_TEST',
    },     
    {   
        text: 'Lights',
        goTo: 'lights-bright',
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        stateToText: (state) => { 
            var texts = [ 'S-8\nKOM', 'S-8\nTsM', 'S-13', 'S-24', 'S-8M\nHE', 'UPK-23', '---', 'FAB\n250', 'FAB\n500', 'KMGU\nAO', 'KMGU\nAT' ] 
            return texts[state]},
        text: 'n/a',
        nameId: 'balVal',
        apiGet: 'PPK800_BAL_DATA',
    },         
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        overflow: false,
        increment: -1,
        maxStatus: 10,
        text: 'Bal-',
        apiSend: 'PPK800_BAL_DATA',
    },     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.blackButton,
        overflow: false,
        maxStatus: 10,
        text: 'Bal+',
        apiSend: 'PPK800_BAL_DATA',
    },     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['off', 'INU'],
        apiSend: 'PPK800_INU_POWER',
    },      
]


buttonsAux2 = [
    {   
        text: '<- Back',
        goTo: 'wall',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.yellowButton,
        text: 'LWS\nOper',
        maxStatus: 0,
        apiGet: 'LWS_OPER',
        sendState: false,
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'LWS'],
        apiSend: 'LWS_POWER',
    },     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        maxStatus: 0,
        sendState: false,
        text: 'LWS\ntest',
        apiSend: 'LWS_TEST',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'ekranCover',
        text: 'Cover\nv',
        apiSend: 'ELEC_HYD_TRAN_EKRAN_POWER_COVER',
    },   

    {   
        text: 'AUX',
        goTo: 'aux1',
    },
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'u26pwr_cover',
        text: 'Cover\nv',
        apiSend: 'UV26_POWER_COVER',
    },   
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.grayButton,
        nameId: 'u26test_cover',
        text: 'Cover\nv',
        apiSend: 'UV26_TEST_COVER',
    },   
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: +4095,
        maxStatus: 65535,
        overflow: false,
        text: '+\nRear AUX\nLight',
        apiSend: 'ELEC_AUX_BRIGHTNESS',
        dynamicState: true,
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'EkrHydTrns'],
        apiSend: 'ELEC_HYD_TRAN_EKRAN_POWER',
    },  
    {   
        text: 'Lights',
        goTo: 'lights-bright',
    },  
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'U26-PWR'],
        apiSend: 'UV26_POWER',
    },     
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'TEST'],
        apiSend: 'UV26_TEST',
    },     
    {   
        type: buttonLogic.types.textToggle,
        defaultStatus: 0,
        scheme: buttonLogic.colorScheme.blackButton,
        increment: -4095,
        maxStatus: 65535,
        overflow: false,
        text: '-\nRear AUX\nLight',
        apiSend: 'ELEC_AUX_BRIGHTNESS',
        dynamicState: true,
    },    
    {   
        type: buttonLogic.types.textToggle,
        scheme: buttonLogic.colorScheme.switch,
        inversed: true,
        text: ['OFF', 'RearLight'],
        apiSend: 'ELEC_AUX_LIGHTS',
    },      
]


module.exports = {
    name: "deck15-ka-50",
    namespaces: [
        { name: 'default',               buttons: buttonsDefault},
        { name: 'hud',                   buttons: buttonsHud},
        { name: 'overhead',              buttons: buttonsOverhead},
        { name: 'front',                 buttons: buttonsFront},
        { name: 'datalink',              buttons: buttonsDatalink},
        { name: 'counter',               buttons: buttonsCounter},
        { name: 'land',                  buttons: buttonsLand},
        { name: 'weapons',               buttons: buttonsWeapons},
        { name: 'arbis',                 buttons: buttonsArbis},
        { name: 'pvi800-1',              buttons: buttonsPvio800_1},
        { name: 'pvi800-2',              buttons: buttonsPvio800_2},
        { name: 'pvi800-3',              buttons: buttonsPvio800_3},
        { name: 'ap',                    buttons: buttonsAp},
        { name: 'flare',                 buttons: buttonsFlare},
        { name: 'vhf1',                  buttons: buttonsVhf1},
        { name: 'wall',                  buttons: buttonsWall},
        { name: 'wall-electrical1',      buttons: buttonsWallEl1},   
        { name: 'wall-pumps',            buttons: buttonsWallPumps},
        { name: 'wall-fuel',             buttons: buttonsWallFuel},        
        { name: 'wall-radio',            buttons: buttonsWallRadio},
        { name: 'wall-eject',            buttons: buttonsWallEject},
        { name: 'wall-fire',             buttons: buttonsWallFire},
        { name: 'wall-equip',            buttons: buttonsWallEquip},
        { name: 'wall-governors-lights', buttons: buttonsWallGovernors},        
        { name: 'aux1',                  buttons: buttonsAux1},
        { name: 'aux2',                  buttons: buttonsAux2},
        { name: 'lights-bright',         buttons: buttonsLightsBrightness},
        { name: 'vhf2',                  buttons: buttonsVhf2},
        { name: 'vhf2freq',              buttons: buttonsVhf2freq},
        { name: 'targeting',             buttons: buttonsTargeting},
        { name: 'engine',                buttons: buttonsEngineApu},
        
    ]
}

